### PR TITLE
Buck fix

### PR DESCRIPTION
**Pull request by NGdev1**

### CODE REVIEW

**Comment by NGdev1** [comment]
fixed

**Comment by swift2geek** [comment]
I tried with/without your fixes, but have the same error:  ~/Projects/Telegram-iOS   master release-6.3 ●  buck project
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:146:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 146
		apple_binary(name = "AppBinary", visibility = [..."], <4 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 152, in apple_binary
		app_binary_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 28, in app_binary_configs
		bundle_identifier(suffix = "")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:163:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 163
		apple_bundle(name = "Telegram", visibility = ["...:"], <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 172, in apple_bundle
		app_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 206, in app_info_plist_substitutions
		bundle_identifier(suffix = "")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:186:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 186
		apple_binary(name = "ShareBinary", srcs = glob(..."]), <4 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 191, in apple_binary
		share_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 51, in share_extension_configs
		bundle_identifier(suffix = ".Share")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:213:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 213
		apple_bundle(name = "ShareExtension", binary = ...", <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 218, in apple_bundle
		share_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 222, in share_extension_info_plist_substitutions
		bundle_identifier(suffix = ".Share")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:226:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 226
		apple_binary(name = "WidgetBinary", srcs = glob..."]), <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 231, in apple_binary
		widget_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 71, in widget_extension_configs
		bundle_identifier(suffix = ".Widget")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:259:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 259
		apple_bundle(name = "WidgetExtension", binary =...", <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 264, in apple_bundle
		widget_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 236, in widget_extension_info_plist_substitutions
		bundle_identifier(suffix = ".Widget")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:272:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 272
		apple_binary(name = "NotificationContentBinar...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 277, in apple_binary
		notification_content_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 91, in notification_content_extension_configs
		bundle_identifier(suffix = ".NotificationContent")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:303:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 303
		apple_bundle(name = "NotificationContentExten...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 308, in apple_bundle
		notification_content_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 251, in notification_content_extension_info_plist_substitutions
		bundle_identifier(suffix = ".NotificationContent")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:316:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 316
		apple_binary(name = "NotificationServiceBinar...", <8 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 326, in apple_binary
		notification_service_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 111, in notification_service_extension_configs
		bundle_identifier(suffix = ".NotificationService")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:363:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 363
		apple_bundle(name = "NotificationServiceExten...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 368, in apple_bundle
		notification_service_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 265, in notification_service_extension_info_plist_substitutions
		bundle_identifier(suffix = ".NotificationService")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:376:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 376
		apple_binary(name = "IntentsBinary", srcs = glo..."]), <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 381, in apple_binary
		intents_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 131, in intents_extension_configs
		bundle_identifier(suffix = ".SiriIntents")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:414:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 414
		apple_bundle(name = "IntentsExtension", binary ...", <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 419, in apple_bundle
		intents_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 279, in intents_extension_info_plist_substitutions
		bundle_identifier(suffix = ".SiriIntents")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
WARNING: /Users/swift2geek/Projects/Telegram-iOS/Config/buck_rule_macros.bzl:314:17: glob's 'include' attribute is empty. Such calls are expensive and unnecessary. Please use an empty list ([]) instead.
WARNING: /Users/swift2geek/Projects/Telegram-iOS/Config/buck_rule_macros.bzl:314:17: glob's 'include' attribute is empty. Such calls are expensive and unnecessary. Please use an empty list ([]) instead.
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:444:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 444
		apple_binary(name = "WatchAppExtensionBinary", <7 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 472, in apple_binary
		watch_extension_binary_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 152, in watch_extension_binary_configs
		bundle_identifier(suffix = ".watchkitapp.watchkite...")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:484:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 484
		apple_bundle(name = "WatchAppExtension", binary...", <4 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 489, in apple_bundle
		watch_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 295, in watch_extension_info_plist_substitutions
		bundle_identifier(suffix = ".watchkitapp.watchkite...")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:516:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 516
		apple_binary(name = "WatchAppBinary", configs =...(), ..."])
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 518, in apple_binary
		watch_binary_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 174, in watch_binary_configs
		bundle_identifier(suffix = ".watchkitapp")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/BUCK:527:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 527
		apple_bundle(name = "WatchApp", binary = ":Watc...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/BUCK", line 535, in apple_bundle
		watch_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 310, in watch_info_plist_substitutions
		bundle_identifier(suffix = ".watchkitapp")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
Cannot evaluate file /Users/swift2geek/Projects/Telegram-iOS/BUCK
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:146:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 146
		apple_binary(name = "AppBinary", visibility = [..."], <4 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 151, in apple_binary
		app_binary_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 28, in app_binary_configs
		bundle_identifier(suffix = "")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:162:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 162
		apple_bundle(name = "Telegram", visibility = ["..."], <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 171, in apple_bundle
		app_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 206, in app_info_plist_substitutions
		bundle_identifier(suffix = "")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:185:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 185
		apple_binary(name = "ShareBinary", srcs = glob(..."]), <4 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 190, in apple_binary
		share_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 51, in share_extension_configs
		bundle_identifier(suffix = ".Share")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:212:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 212
		apple_bundle(name = "ShareExtension", binary = ...", <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 217, in apple_bundle
		share_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 222, in share_extension_info_plist_substitutions
		bundle_identifier(suffix = ".Share")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:225:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 225
		apple_binary(name = "WidgetBinary", srcs = glob..."]), <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 230, in apple_binary
		widget_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 71, in widget_extension_configs
		bundle_identifier(suffix = ".Widget")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:258:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 258
		apple_bundle(name = "WidgetExtension", binary =...", <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 263, in apple_bundle
		widget_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 236, in widget_extension_info_plist_substitutions
		bundle_identifier(suffix = ".Widget")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:271:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 271
		apple_binary(name = "NotificationContentBinar...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 276, in apple_binary
		notification_content_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 91, in notification_content_extension_configs
		bundle_identifier(suffix = ".NotificationContent")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:302:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 302
		apple_bundle(name = "NotificationContentExten...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 307, in apple_bundle
		notification_content_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 251, in notification_content_extension_info_plist_substitutions
		bundle_identifier(suffix = ".NotificationContent")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:315:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 315
		apple_binary(name = "NotificationServiceBinar...", <8 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 325, in apple_binary
		notification_service_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 111, in notification_service_extension_configs
		bundle_identifier(suffix = ".NotificationService")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:362:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 362
		apple_bundle(name = "NotificationServiceExten...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 367, in apple_bundle
		notification_service_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 265, in notification_service_extension_info_plist_substitutions
		bundle_identifier(suffix = ".NotificationService")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:375:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 375
		apple_binary(name = "IntentsBinary", srcs = glo..."]), <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 380, in apple_binary
		intents_extension_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 131, in intents_extension_configs
		bundle_identifier(suffix = ".SiriIntents")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:413:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 413
		apple_bundle(name = "IntentsExtension", binary ...", <5 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 418, in apple_bundle
		intents_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 279, in intents_extension_info_plist_substitutions
		bundle_identifier(suffix = ".SiriIntents")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:443:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 443
		apple_binary(name = "WatchAppExtensionBinary", <7 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 471, in apple_binary
		watch_extension_binary_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 152, in watch_extension_binary_configs
		bundle_identifier(suffix = ".watchkitapp.watchkite...")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:483:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 483
		apple_bundle(name = "WatchAppExtension", binary...", <4 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 488, in apple_bundle
		watch_extension_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 295, in watch_extension_info_plist_substitutions
		bundle_identifier(suffix = ".watchkitapp.watchkite...")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:515:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 515
		apple_binary(name = "WatchAppBinary", configs =...(), ..."])
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 517, in apple_binary
		watch_binary_configs()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 174, in watch_binary_configs
		bundle_identifier(suffix = ".watchkitapp")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined
ERROR: /Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK:526:1: Traceback (most recent call last):
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 526
		apple_bundle(name = "WatchApp", binary = ":Watc...", <6 more arguments>)
	File "/Users/swift2geek/Projects/Telegram-iOS/Telegram/BUCK", line 534, in apple_bundle
		watch_info_plist_substitutions()
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/configs.bzl", line 310, in watch_info_plist_substitutions
		bundle_identifier(suffix = ".watchkitapp")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 128, in bundle_identifier
		read_config_nonempty("baseApplicationBundleId")
	File "/Users/swift2geek/Projects/Telegram-iOS/Config/utils.bzl", line 67, in read_config_nonempty
		fail(("Configuration parameter custom...))
Configuration parameter custom.baseApplicationBundleId should be defined

**Comment by NGdev1** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/issues/219
i found the solution in this issue

**Comment by ali-fareed** [comment]
The project switch to Bazel as the main build system.

**Pull request closed without merging**
